# .travis.yml file
language: node_js

install:
  - npm install
  - npm ls

node_js:
  - "8"
before_install:
  - npm install -g npm@latest

services: mongodb

cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm test



