# .travis.yml file
language: node_js
node_js:
  - 8
  - 6
  - 4
  - 0.12
before_install:
  - npm install -g npm@latest
services: mongodb
cache:
  directories:
    - "node_modules"
sudo: false
install:
  -npm install -g npm@2
script:
  - npm test



